"""
LangGraph Generator - LangGraph 代码生成器

从 Workflow 对象生成可执行的 LangGraph Agent 代码。
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Optional

from ..schemas import Workflow, WorkflowStep


@dataclass
class GeneratedCode:
    """生成的代码"""
    
    main_code: str
    """主代码"""
    
    test_code: Optional[str] = None
    """测试代码"""
    
    requirements: list[str] = None
    """依赖列表"""
    
    def __post_init__(self):
        if self.requirements is None:
            self.requirements = ["langgraph>=0.2.0", "langchain>=0.1.0"]


class LangGraphGenerator:
    """LangGraph 代码生成器
    
    将 Workflow 转换为 LangGraph Agent 代码。
    
    Example:
        >>> generator = LangGraphGenerator()
        >>> code = generator.generate(workflow)
        >>> print(code.main_code)
    """
    
    def __init__(self):
        """初始化生成器"""
        pass
    
    def generate(
        self,
        workflow: Workflow,
        include_tests: bool = False,
        include_comments: bool = True,
    ) -> GeneratedCode:
        """生成 LangGraph 代码
        
        Args:
            workflow: 工作流对象
            include_tests: 是否生成测试代码
            include_comments: 是否包含注释
            
        Returns:
            生成的代码
        """
        main_code = self._generate_main(workflow, include_comments)
        test_code = self._generate_tests(workflow) if include_tests else None
        
        return GeneratedCode(
            main_code=main_code,
            test_code=test_code,
            requirements=self._collect_requirements(workflow),
        )
    
    def _generate_main(self, workflow: Workflow, include_comments: bool) -> str:
        """生成主代码"""
        
        # 收集所有工具
        all_tools = set()
        for step in workflow.steps:
            all_tools.update(step.tools_used)
        
        # 生成类名
        class_name = self._to_class_name(workflow.name)
        
        code_parts = []
        
        # 文件头
        code_parts.append(self._generate_header(workflow, include_comments))
        
        # 导入
        code_parts.append(self._generate_imports())
        
        # State 定义
        code_parts.append(self._generate_state(workflow, class_name))
        
        # 工具定义占位
        code_parts.append(self._generate_tool_stubs(all_tools, include_comments))
        
        # 节点函数
        code_parts.append(self._generate_nodes(workflow, include_comments))
        
        # 条件函数
        code_parts.append(self._generate_conditions(workflow, include_comments))
        
        # Graph 构建
        code_parts.append(self._generate_graph(workflow, class_name))
        
        # Main 入口
        code_parts.append(self._generate_main_entry(class_name))
        
        return "\n\n".join(code_parts)
    
    def _generate_header(self, workflow: Workflow, include_comments: bool) -> str:
        """生成文件头"""
        if not include_comments:
            return '"""Auto-generated LangGraph Agent"""'
        
        return f'''"""
{workflow.name} - Auto-generated LangGraph Agent

Description: {workflow.description or 'N/A'}
Goal: {workflow.goal}
Steps: {len(workflow.steps)}
Generated by: Agent Inspector

WARNING: This is auto-generated code. Review and customize before use.
"""'''
    
    def _generate_imports(self) -> str:
        """生成导入语句"""
        return '''from typing import TypedDict, Annotated, Literal
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from langchain_core.messages import HumanMessage, AIMessage, BaseMessage
import operator'''
    
    def _generate_state(self, workflow: Workflow, class_name: str) -> str:
        """生成 State 类型定义"""
        
        # 收集状态字段
        fields = [
            '    messages: Annotated[list[BaseMessage], operator.add]',
            '    current_step: int',
            '    completed_steps: list[int]',
        ]
        
        # 从工作流步骤推断额外状态
        for step in workflow.steps:
            if step.output_summary:
                field_name = self._to_snake_case(f"step_{step.round_number}_output")
                fields.append(f'    {field_name}: str | None')
        
        fields_str = "\n".join(fields)
        
        return f'''class {class_name}State(TypedDict):
    """Agent 状态"""
{fields_str}'''
    
    def _generate_tool_stubs(self, tools: set[str], include_comments: bool) -> str:
        """生成工具函数占位"""
        if not tools:
            return "# No tools detected"
        
        parts = ["# =============================================================================",
                 "# Tool Functions (TODO: Implement these)",
                 "# ============================================================================="]
        
        for tool in sorted(tools):
            func_name = self._to_snake_case(tool)
            if include_comments:
                parts.append(f'''
def {func_name}(*args, **kwargs):
    """Tool: {tool}
    
    TODO: Implement this tool function.
    """
    raise NotImplementedError("Tool {tool} not implemented")''')
            else:
                parts.append(f'''
def {func_name}(*args, **kwargs):
    raise NotImplementedError("Tool {tool} not implemented")''')
        
        return "\n".join(parts)
    
    def _generate_nodes(self, workflow: Workflow, include_comments: bool) -> str:
        """生成节点函数"""
        parts = ["# =============================================================================",
                 "# Node Functions",
                 "# ============================================================================="]
        
        for step in workflow.steps:
            func_name = f"node_step_{step.round_number}"
            
            # 工具调用代码
            tool_calls = ""
            if step.tools_used:
                tool_calls = "\n    ".join([
                    f"# Call: {self._to_snake_case(tool)}(...)"
                    for tool in step.tools_used
                ])
            
            if include_comments:
                parts.append(f'''
def {func_name}(state: dict) -> dict:
    """Step {step.round_number}: {step.goal}
    
    Action: {step.action_summary or 'N/A'}
    Tools: {', '.join(step.tools_used) if step.tools_used else 'None'}
    """
    # TODO: Implement step logic
    {tool_calls if tool_calls else "pass"}
    
    return {{
        "current_step": {step.round_number},
        "completed_steps": state.get("completed_steps", []) + [{step.round_number}],
    }}''')
            else:
                parts.append(f'''
def {func_name}(state: dict) -> dict:
    {tool_calls if tool_calls else "pass"}
    return {{"current_step": {step.round_number}, "completed_steps": state.get("completed_steps", []) + [{step.round_number}]}}''')
        
        return "\n".join(parts)
    
    def _generate_conditions(self, workflow: Workflow, include_comments: bool) -> str:
        """生成条件函数"""
        # 检查是否有决策点
        has_decisions = any(step.decision_points for step in workflow.steps)
        
        if not has_decisions:
            return "# No conditional routing detected"
        
        parts = ["# =============================================================================",
                 "# Conditional Routing",
                 "# ============================================================================="]
        
        for step in workflow.steps:
            if step.decision_points:
                func_name = f"route_after_step_{step.round_number}"
                decisions = step.decision_points
                
                parts.append(f'''
def {func_name}(state: dict) -> Literal["continue", "end"]:
    """Route after step {step.round_number}
    
    Decision points:
    {chr(10).join(f"  - {d}" for d in decisions)}
    """
    # TODO: Implement routing logic
    return "continue"''')
        
        return "\n".join(parts)
    
    def _generate_graph(self, workflow: Workflow, class_name: str) -> str:
        """生成 Graph 构建代码"""
        
        # 构建节点添加代码
        node_adds = []
        for step in workflow.steps:
            node_adds.append(f'    graph.add_node("step_{step.round_number}", node_step_{step.round_number})')
        
        # 构建边添加代码
        edge_adds = []
        for i, step in enumerate(workflow.steps):
            if i == 0:
                edge_adds.append(f'    graph.set_entry_point("step_{step.round_number}")')
            
            if i < len(workflow.steps) - 1:
                next_step = workflow.steps[i + 1]
                if step.decision_points:
                    edge_adds.append(f'    graph.add_conditional_edges("step_{step.round_number}", route_after_step_{step.round_number})')
                else:
                    edge_adds.append(f'    graph.add_edge("step_{step.round_number}", "step_{next_step.round_number}")')
            else:
                edge_adds.append(f'    graph.add_edge("step_{step.round_number}", END)')
        
        nodes_str = "\n".join(node_adds)
        edges_str = "\n".join(edge_adds)
        
        return f'''# =============================================================================
# Graph Construction
# =============================================================================

def build_graph() -> StateGraph:
    """Build the LangGraph workflow"""
    graph = StateGraph({class_name}State)
    
    # Add nodes
{nodes_str}
    
    # Add edges
{edges_str}
    
    return graph.compile()


# Compiled graph instance
workflow_graph = build_graph()'''
    
    def _generate_main_entry(self, class_name: str) -> str:
        """生成 main 入口"""
        return f'''# =============================================================================
# Main Entry
# =============================================================================

def run(initial_message: str) -> dict:
    """Run the workflow
    
    Args:
        initial_message: Initial user message
        
    Returns:
        Final state
    """
    initial_state = {{
        "messages": [HumanMessage(content=initial_message)],
        "current_step": 0,
        "completed_steps": [],
    }}
    
    result = workflow_graph.invoke(initial_state)
    return result


if __name__ == "__main__":
    result = run("Start workflow")
    print(f"Completed steps: {{result['completed_steps']}}")'''
    
    def _generate_tests(self, workflow: Workflow) -> str:
        """生成测试代码"""
        class_name = self._to_class_name(workflow.name)
        
        return f'''"""
Tests for {workflow.name}
"""

import pytest
from .{self._to_snake_case(workflow.name)} import workflow_graph, run, {class_name}State


def test_graph_compiles():
    """Test that the graph compiles successfully"""
    assert workflow_graph is not None


def test_initial_state():
    """Test running with initial state"""
    result = run("Test message")
    assert "completed_steps" in result
    assert len(result["completed_steps"]) == {len(workflow.steps)}


@pytest.mark.parametrize("step_num", {list(range(1, len(workflow.steps) + 1))})
def test_step_execution(step_num):
    """Test individual step execution"""
    # TODO: Add step-specific tests
    pass
'''
    
    def _collect_requirements(self, workflow: Workflow) -> list[str]:
        """收集依赖"""
        reqs = [
            "langgraph>=0.2.0",
            "langchain-core>=0.1.0",
        ]
        
        # 检查是否需要特定工具的依赖
        all_tools = set()
        for step in workflow.steps:
            all_tools.update(step.tools_used)
        
        # 常见工具的依赖映射
        tool_deps = {
            "web_search": "langchain-community>=0.1.0",
            "tavily": "tavily-python>=0.3.0",
            "serpapi": "google-search-results>=2.4.0",
        }
        
        for tool in all_tools:
            tool_lower = tool.lower()
            for key, dep in tool_deps.items():
                if key in tool_lower:
                    reqs.append(dep)
        
        return list(set(reqs))
    
    def _to_class_name(self, name: str) -> str:
        """转换为类名 (PascalCase)"""
        # 移除特殊字符，转换为 PascalCase
        words = re.split(r'[-_\s]+', name)
        return "".join(word.capitalize() for word in words)
    
    def _to_snake_case(self, name: str) -> str:
        """转换为蛇形命名"""
        # 移除特殊字符
        name = re.sub(r'[^\w\s-]', '', name)
        # 转换为小写蛇形
        name = re.sub(r'[-\s]+', '_', name)
        name = re.sub(r'([A-Z])', r'_\1', name)
        return name.lower().strip('_')
