"""
LangGraph Workflow Template — Auto-generated by FlowCraft Distill.

This is a reference template showing the structure of generated LangGraph code.
Actual generation is done by: flowcraft-distill extract --from-yaml <file> --langgraph

The generated code creates a state machine where:
- Each workflow phase becomes a graph node
- Phase transitions are edges
- State is tracked via a TypedDict
- Tools are stub functions that you implement

Prerequisites:
    pip install langgraph langchain-core
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, Literal, TypedDict

from langgraph.graph import END, START, StateGraph


# ── State ───────────────────────────────────────────────────────────────────

class WorkflowState(TypedDict):
    """State tracked across all phases."""

    phase: Literal["research", "implement", "test", "done"]
    messages: Annotated[list[dict], operator.add]
    context: dict[str, Any]
    # Add custom state variables from your workflow DSL


# ── Phase Nodes ─────────────────────────────────────────────────────────────

def research_node(state: WorkflowState) -> dict:
    """
    Phase: Research
    Entry: always (first phase)
    Exit: requirements gathered
    """
    # Step 1: Read project structure
    #   Tools: read_file, list_dir
    # Step 2: Analyze dependencies
    #   Tools: grep_search, semantic_search

    # TODO: Implement this phase
    return {"phase": "implement"}


def implement_node(state: WorkflowState) -> dict:
    """
    Phase: Implementation
    Entry: research complete
    Exit: code written
    """
    # Step 1: Create/modify files
    #   Tools: create_file, replace_string_in_file
    # Step 2: Install dependencies
    #   Tools: run_in_terminal

    # TODO: Implement this phase
    return {"phase": "test"}


def test_node(state: WorkflowState) -> dict:
    """
    Phase: Testing
    Entry: implementation complete
    Exit: tests pass
    """
    # Step 1: Run tests
    #   Tools: run_in_terminal
    # Step 2: Fix errors (loop)
    #   Decision: tests pass → done | fail → implement

    # TODO: Implement this phase
    return {"phase": "done"}


# ── Graph Construction ──────────────────────────────────────────────────────

def build_workflow_graph() -> StateGraph:
    """Build the LangGraph workflow."""
    graph = StateGraph(WorkflowState)

    graph.add_node("research", research_node)
    graph.add_node("implement", implement_node)
    graph.add_node("test", test_node)

    graph.add_edge(START, "research")
    graph.add_edge("research", "implement")
    graph.add_edge("implement", "test")
    graph.add_edge("test", END)

    return graph.compile()


# ── Main ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    graph = build_workflow_graph()

    initial_state = {
        "phase": "research",
        "messages": [],
        "context": {},
    }

    print("Running workflow...")
    result = graph.invoke(initial_state)
    print(f"Final phase: {result.get('phase', 'unknown')}")
